# Generated by Django 2.1.2 on 2018-10-23 07:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Letters',
            new_name='Letter',
        ),
        migrations.RenameModel(
            old_name='Properties',
            new_name='Property',
        ),
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
