# Generated by Django 2.1.2 on 2018-10-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0002_auto_20181023_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='created_at',
        ),
    ]
